//! VM guest-tools integration (per-box opt-in).
//!
//! NASty ships the QEMU guest agent **always-on** — it's effectively
//! free because it reuses the full `qemu` already bundled for the VM
//! feature (see `appliance-base.nix`). The heavier hypervisor
//! integrations — VMware (`open-vm-tools`, ~500 MiB closure) and Hyper-V
//! — are per-box opt-in so they stay out of the base image.
//!
//! Mirrors the `passthrough` module's overlay pattern:
//!   state file:    /var/lib/nasty/guest-tools.json   ({ "enabled": bool })
//!   engine writes: /etc/nixos/guest-tools.nix
//!   wrapper flake imports guest-tools.nix (pathExists-guarded)
//!
//! Unlike Secure Boot, the overlay needs **no extra flake input** —
//! `virtualisation.vmware.guest` / `virtualisation.hypervGuest` are
//! stock nixpkgs modules — so there are no cross-version lock-entry
//! hazards. Enabling triggers an immediate `nixos-rebuild switch`
//! (transient systemd unit, mirroring `update::apply`) so `open-vm-tools`
//! substitutes from the binary cache and `vmtoolsd` starts without a
//! reboot.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex;
use tracing::{info, warn};

const STATE_PATH: &str = "/var/lib/nasty/guest-tools.json";
const NIX_PATH: &str = "/etc/nixos/guest-tools.nix";
const REBUILD_UNIT: &str = "nasty-guest-tools-rebuild";
const REBUILD_SCRIPT: &str = "/tmp/nasty-guest-tools-rebuild.sh";

/// Lock held only across state read/writes so concurrent RPCs can't
/// tear the state file. Lazily initialized — no global setup.
static STATE_LOCK: Mutex<()> = Mutex::const_new(());

/// Persistent opt-in flag. The QEMU guest agent is always-on and is
/// deliberately NOT governed by this — it covers KVM/Proxmox for free.
#[derive(Debug, Clone, Default, Serialize, Deserialize, JsonSchema)]
pub struct GuestToolsConfig {
    /// Whether the heavy hypervisor integrations (VMware open-vm-tools,
    /// Hyper-V) are enabled on this box.
    pub enabled: bool,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
pub struct GuestToolsUpdate {
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct GuestToolsStatus {
    /// Persisted opt-in flag.
    pub enabled: bool,
    /// Hypervisor reported by `systemd-detect-virt` (e.g. `vmware`,
    /// `microsoft`, `kvm`, `qemu`, `oracle`, `none`).
    pub hypervisor: String,
    /// True when running under any detected hypervisor.
    pub is_vm: bool,
    /// `idle` | `running` | `failed` — state of the most recent
    /// guest-tools rebuild, read from the transient unit.
    pub rebuild_state: String,
    /// Recent rebuild log lines, surfaced while running or on failure.
    pub log_tail: Option<String>,
}

pub async fn load() -> GuestToolsConfig {
    let _guard = STATE_LOCK.lock().await;
    nasty_common::load_singleton_or_recover(STATE_PATH).await
}

/// `systemd-detect-virt` → lowercased token, or `none` on bare metal /
/// when the tool is unavailable. Captures stdout regardless of exit code
/// (detect-virt exits non-zero with "none" on bare metal). Never errors.
pub async fn detect_hypervisor() -> String {
    match tokio::process::Command::new("systemd-detect-virt")
        .output()
        .await
    {
        Ok(o) => {
            let v = String::from_utf8_lossy(&o.stdout).trim().to_lowercase();
            if v.is_empty() { "none".to_string() } else { v }
        }
        Err(_) => "none".to_string(),
    }
}

/// Pure renderer for `/etc/nixos/guest-tools.nix`. Always emits a valid
/// module body, even when disabled (keeps the wrapper import contract
/// stable regardless of state). `hv` is the detected hypervisor token.
pub fn render_nix_module(enabled: bool, hv: &str) -> String {
    if !enabled {
        return "# Generated by nasty-engine. VM guest tools disabled.\n\
                # Source of truth: /var/lib/nasty/guest-tools.json (toggle in WebUI).\n\
                { ... }: { }\n"
            .to_string();
    }
    let body = guest_module_lines(hv);
    format!(
        "# Generated by nasty-engine. VM guest tools enabled.\n\
         #\n\
         # Detected hypervisor: {hv}. open-vm-tools / Hyper-V integration are\n\
         # opt-in here to keep them out of the base image; the QEMU guest agent\n\
         # ships always-on (appliance-base.nix). Source of truth:\n\
         # /var/lib/nasty/guest-tools.json — toggle via the WebUI System page.\n\
         {{ ... }}: {{\n\
         {body}}}\n"
    )
}

/// Which `virtualisation.*.guest` knobs to set for a detected hypervisor.
/// Each module self-gates on `ConditionVirtualization`, so an over-broad
/// choice is harmless at runtime — only the closure cost differs.
fn guest_module_lines(hv: &str) -> String {
    match hv {
        "vmware" => "  virtualisation.vmware.guest.enable = true;\n".to_string(),
        "microsoft" => "  virtualisation.hypervGuest.enable = true;\n".to_string(),
        // KVM/QEMU are already covered by the always-on QEMU guest agent,
        // so toggling here is a no-op rather than a double-declare.
        "kvm" | "qemu" => {
            "  # KVM/QEMU — already covered by the always-on QEMU guest agent.\n".to_string()
        }
        // Unknown / none: the operator explicitly opted in but detection
        // was inconclusive, so enable both heavy integrations as a
        // catch-all. Each self-gates, so it's harmless on the wrong
        // hypervisor — only the closure is larger.
        _ => concat!(
            "  virtualisation.vmware.guest.enable = true;\n",
            "  virtualisation.hypervGuest.enable = true;\n",
        )
        .to_string(),
    }
}

/// Render `cfg`/`hv` to `/etc/nixos/guest-tools.nix`. On a fresh install
/// before rebootstrap (`/etc/nixos` absent) this is a no-op — state.json
/// still persists so the next rebootstrap picks it up.
async fn write_nix_file(enabled: bool, hv: &str) -> Result<(), String> {
    let Some(nix_dir) = std::path::Path::new(NIX_PATH).parent() else {
        return Err(format!("{NIX_PATH}: no parent dir"));
    };
    if !nix_dir.exists() {
        return Ok(());
    }
    let body = render_nix_module(enabled, hv);
    tokio::fs::write(NIX_PATH, body)
        .await
        .map_err(|e| format!("write {NIX_PATH}: {e}"))
}

/// Persist the opt-in flag, regenerate the overlay, and kick off an
/// async `nixos-rebuild switch` so the change applies without a reboot.
/// Returns the post-write status; the rebuild runs in the background —
/// poll [`status`] for progress.
pub async fn set_and_apply(update: GuestToolsUpdate) -> Result<GuestToolsStatus, String> {
    let hv = detect_hypervisor().await;

    // Don't stack a second rebuild on top of a running one.
    if rebuild_state().await.0 == "running" {
        return Err("a guest-tools rebuild is already running".to_string());
    }

    {
        let _guard = STATE_LOCK.lock().await;
        let cfg = GuestToolsConfig {
            enabled: update.enabled,
        };
        let json = serde_json::to_string_pretty(&cfg).map_err(|e| format!("serialize: {e}"))?;
        if let Some(parent) = std::path::Path::new(STATE_PATH).parent()
            && let Err(e) = tokio::fs::create_dir_all(parent).await
        {
            warn!("create {}: {e}", parent.display());
        }
        tokio::fs::write(STATE_PATH, json)
            .await
            .map_err(|e| format!("write {STATE_PATH}: {e}"))?;
        write_nix_file(update.enabled, &hv).await?;
    }

    spawn_rebuild().await?;
    info!(
        "VM guest tools {} (hypervisor: {hv}); rebuild started",
        if update.enabled {
            "enabled"
        } else {
            "disabled"
        }
    );
    Ok(status().await)
}

/// Launch `nixos-rebuild switch` as a transient systemd unit so it runs
/// outside the engine's `ProtectSystem` sandbox (mirrors `update::apply`).
/// No GitHub token is needed: the overlay changes no flake inputs, so the
/// switch resolves against the already-locked flake and pulls
/// `open-vm-tools` from the binary cache.
async fn spawn_rebuild() -> Result<(), String> {
    // Best-effort: clear any prior failed unit so the name is reusable.
    nasty_common::cmd::try_run("systemctl", &["reset-failed", REBUILD_UNIT]).await;

    let tmpdir_line = match crate::update::read_update_build_dir().await {
        Some(dir) => format!("export TMPDIR={dir}\nmkdir -p \"$TMPDIR\" || true\n"),
        None => String::new(),
    };

    let script = format!(
        r#"#!/bin/bash
set -euo pipefail
export PATH="/run/current-system/sw/bin:$PATH"
{tmpdir_line}echo "==> Applying VM guest tools (nixos-rebuild switch)..."
_RC=0
NIXOS_INSTALL_BOOTLOADER=0 nixos-rebuild switch --flake /etc/nixos#nasty || _RC=$?
if [ "$_RC" -ne 0 ]; then
    echo "==> nixos-rebuild switch failed (exit $_RC)."
    echo "--- journalctl -u nixos-rebuild-switch-to-configuration -n 40 ---"
    journalctl -u nixos-rebuild-switch-to-configuration --no-pager -n 40 || true
    exit "$_RC"
fi
echo "==> VM guest tools applied."
"#
    );

    tokio::fs::write(REBUILD_SCRIPT, &script)
        .await
        .map_err(|e| format!("write rebuild script: {e}"))?;

    let path = std::env::var("PATH").unwrap_or_default();
    let output = tokio::process::Command::new("systemd-run")
        .args([
            "--unit",
            REBUILD_UNIT,
            "--no-block",
            "--description",
            "NASty VM guest-tools rebuild",
            "--property=Type=oneshot",
            "--property=StandardOutput=journal",
            "--property=StandardError=journal",
            "--setenv",
        ])
        .arg(format!("PATH={path}"))
        .args(["--", "bash", REBUILD_SCRIPT])
        .output()
        .await
        .map_err(|e| format!("systemd-run: {e}"))?;

    if !output.status.success() {
        return Err(format!(
            "failed to start rebuild: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    Ok(())
}

/// Read the transient rebuild unit's state as `(state, log_tail)`,
/// where `state` ∈ `idle` | `running` | `failed`. A successful oneshot
/// goes back to `inactive`, which reads as `idle`.
async fn rebuild_state() -> (String, Option<String>) {
    let active = match tokio::process::Command::new("systemctl")
        .args(["show", REBUILD_UNIT, "-p", "ActiveState", "-p", "Result"])
        .output()
        .await
    {
        Ok(o) => {
            let s = String::from_utf8_lossy(&o.stdout);
            let mut active_state = "";
            let mut result = "";
            for line in s.lines() {
                if let Some(v) = line.strip_prefix("ActiveState=") {
                    active_state = v.trim();
                } else if let Some(v) = line.strip_prefix("Result=") {
                    result = v.trim();
                }
            }
            (active_state.to_string(), result.to_string())
        }
        Err(_) => return ("idle".to_string(), None),
    };

    let state = match active.0.as_str() {
        "active" | "activating" | "reloading" | "deactivating" => "running",
        "failed" => "failed",
        _ if active.1 == "timeout" || active.1 == "exit-code" || active.1 == "signal" => "failed",
        _ => "idle",
    };

    let log_tail = if state == "running" || state == "failed" {
        tokio::process::Command::new("journalctl")
            .args(["-u", REBUILD_UNIT, "-n", "30", "--no-pager", "-o", "cat"])
            .output()
            .await
            .ok()
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
            .filter(|s| !s.is_empty())
    } else {
        None
    };

    (state.to_string(), log_tail)
}

pub async fn status() -> GuestToolsStatus {
    let cfg = load().await;
    let hv = detect_hypervisor().await;
    let (rebuild_state, log_tail) = rebuild_state().await;
    GuestToolsStatus {
        enabled: cfg.enabled,
        is_vm: hv != "none",
        hypervisor: hv,
        rebuild_state,
        log_tail,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_disabled_is_noop_module() {
        let m = render_nix_module(false, "vmware");
        assert!(m.contains("{ ... }: { }"));
        assert!(m.contains("disabled"));
        assert!(!m.contains("vmware.guest.enable"));
    }

    #[test]
    fn render_vmware_enables_only_vmware() {
        let m = render_nix_module(true, "vmware");
        assert!(m.contains("virtualisation.vmware.guest.enable = true;"));
        assert!(!m.contains("hypervGuest"));
    }

    #[test]
    fn render_hyperv_enables_only_hyperv() {
        let m = render_nix_module(true, "microsoft");
        assert!(m.contains("virtualisation.hypervGuest.enable = true;"));
        assert!(!m.contains("vmware.guest.enable"));
    }

    #[test]
    fn render_kvm_is_noop_already_covered_by_always_on_agent() {
        let m = render_nix_module(true, "kvm");
        assert!(!m.contains("vmware.guest.enable"));
        assert!(!m.contains("hypervGuest.enable"));
        assert!(m.contains("QEMU guest agent"));
    }

    #[test]
    fn render_unknown_enables_both_as_catch_all() {
        for hv in ["none", "oracle", "bochs", ""] {
            let m = render_nix_module(true, hv);
            assert!(
                m.contains("virtualisation.vmware.guest.enable = true;"),
                "vmware missing for hv={hv}"
            );
            assert!(
                m.contains("virtualisation.hypervGuest.enable = true;"),
                "hyperv missing for hv={hv}"
            );
        }
    }

    #[test]
    fn rendered_module_is_a_valid_nix_attrset_function() {
        // Every branch must produce `{ ... }: { ... }` shape.
        for (en, hv) in [
            (false, "vmware"),
            (true, "vmware"),
            (true, "kvm"),
            (true, "none"),
        ] {
            let m = render_nix_module(en, hv);
            assert!(m.contains("{ ... }:"), "not a module fn: en={en} hv={hv}");
            assert!(m.trim_end().ends_with('}'), "unterminated: en={en} hv={hv}");
        }
    }
}
